3s Run npx semantic-release [4:34:35 AM] [semantic-release] › ℹ  Running semantic-release version 24.2.1 [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github" [4:34:35 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github" [4:34:36 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github" [4:34:36 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com) [4:34:36 AM] [semantic-release] › ✘  Failed step "fail" of plugin "@semantic-release/github" [4:34:36 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: Cannot read properties of undefined (reading 'name')     at getFailComment (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/@semantic-release/github/lib/get-fail-comment.js:20:12)     at fail (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/@semantic-release/github/lib/fail.js:58:9)     at async fail (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/@semantic-release/github/index.js:104:3)     at async validator (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/plugins/normalize.js:36:24)     at async file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/plugins/pipeline.js:38:36     at async file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/plugins/pipeline.js:32:5     at async pluginsConfigAccumulator.<computed> [as fail] (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/plugins/index.js:87:11)     at async callFail (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:252:7)     at async Module.default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:282:7)     at async default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/cli.js:55:5) {   pluginName: '@semantic-release/github' } [4:34:36 AM] [semantic-release] › ✘  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration. A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches). These branches must exist on the remote repository.
This may occur if your repository does not have a release branch, such as master or main.

Your configuration for the problematic branches is [].

AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/get-error.js:6:10)
        at file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/branches/index.js:45:19
        at Array.reduce (<anonymous>)
        at default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/branches/index.js:35:46)
        at async run (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:68:22)
        at async Module.default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:278:22)
        at async default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/cli.js:55:5)
    at default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/branches/index.js:67:11)
    at async run (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:68:22)
    at async Module.default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:278:22)
    at async default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/get-error.js:6:10)
        at file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/branches/index.js:45:19
        at Array.reduce (<anonymous>)
        at default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/lib/branches/index.js:35:46)
        at async run (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:68:22)
        at async Module.default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/index.js:278:22)
        at async default (file:///home/runner/work/certiplate-ui-v3-candidate/certiplate-ui-v3-candidate/node_modules/semantic-release/cli.js:55:5) {
      code: 'ERELEASEBRANCHES',
      details: 'A minimum of 1 and a maximum of 3 release branches are required in the [branches configuration](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches). These branches must exist on the remote repository.\n' +
        '\n' +
        'This may occur if your repository does not have a release branch, such as `master` or `main`.\n' +
        '\n' +
        'Your configuration for the problematic branches is `[]`.',
      semanticRelease: true
    }
  ]
}